Attribute VB_Name = "modRibbonStrings"
Option Compare Database
Option Private Module
Option Explicit

Private m_dStrings As Dictionary


'---------------------------------------------------------------------------------------
' Procedure : GetRibbonStrings
' Author    : Adam Waller
' Date      : 10/29/2024
' Purpose   : Return a dictionary of strings for menu labels and descriptions.
'           : Applies any applicable translations before returning strings.
'---------------------------------------------------------------------------------------
'
Public Function GetRibbonStrings() As Dictionary

    ' Start with empty dictionary
    Set m_dStrings = New Dictionary

    ' Add a comment entry so translators don't attempt to edit the strings.
    AddCtl "PLEASE NOTE:", "This file is automatically generated by the add-in. Please do not translate or edit this file directly."

    ' Ribbon tab
    AddCtl "tabVersionControl", "Version Control"

    ' Actions group
    AddCtl "grpActions", "Actions"

        AddCtl "btnShow", "Open Add-in", _
            strSupertip:="Open the main form for the add-in. From the main form you can run an export or build a project from source."

        AddCtl "btnExport", "Export Source Files", _
            strSupertip:="Export all source files for the current project using the current options."

        AddCtl "btnExportVBA", "Export VBA Code", _
            strSupertip:="Export only the components that may contain VBA code. Includes forms, reports, and VBA code modules."

        AddCtl "btnExportSelected", "Export Selected", _
            strSupertip:="Export the database component currently selected in the navigation pane."

        AddCtl "btnBuild", "Build From Source", _
            strSupertip:="Build the current project from source files."

        AddCtl "btnMergeBuild", "Merge Build", _
            strSupertip:="Merge changed source files into the current database."

        AddCtl "btnBuildAs", "Build As…", _
            strSupertip:="Build from source files to a new name or location."

        AddCtl "btnLoadSelected", "Load Selected", _
            strSupertip:="Import from source files the database component currently selected in the navigation pane."

    ' Options group
    AddCtl "grpOptions", "Options"

        AddCtl "btnShowOptions", "View Options", _
            strSupertip:="Open the Options form to view or change options for the current project."

    ' Tools group
    AddCtl "grpTools", "Tools"

        AddCtl "btnOpenSourceFolder", "Source Folder", _
            strSupertip:="Open the source folder for the current project."

        AddCtl "btnOpenExportLog", "Export Log", _
            strSupertip:="Open the most recent export log file."

        AddCtl "btnOpenBuildLog", "Build Log", _
            strSupertip:="Open the most recent build log file."

        ' Advanced Tools menu
        AddCtl "mnuAdvancedTools", "Advanced Tools", _
            strSupertip:="These tools are intended for more advanced development purposes. Please review the documentation for these tools before using them."

            AddCtl "btnGoToLinkAdvancedTools", "View Documentation", _
                strDescription:="See documentation on the purpose and usage of these custom tools..."

            AddCtl "btnLocalizeLibraryReferences", "Localize Library References", _
                strDescription:="Relink add-in library databases to the files located in the same folder as the current database"

            AddCtl "btnRepairColors", "Repair Colors", _
                strDescription:="Rebuild color definition blocks in form objects (See documentation for more info)"

            AddCtl "btnSplitFiles", "Split Files", _
                strDescription:="Duplicate files while preserving Git line history"

            AddCtl "btnActivateHook", "Activate Hook", _
                strDescription:="Enable Access Application hook to report saving of objects and enabling automatic export on save."

            AddCtl "btnReloadRibbon", "Reload Ribbon", _
                strDescription:="Refresh the add-in ribbon menu to reflect changes in XML source"

    ' GitHub Community group
    AddCtl "grpGitHub", "GitHub Community"

        AddCtl "btnGoToLinkHome", "Project Home", _
            strSupertip:="View the add-in project home on GitHub."

        AddCtl "btnGoToLinkDocumentation", "Online Documentation", _
            strSupertip:="View the documentation Wiki on GitHub."

        AddCtl "btnGoToLinkSupport", "Support Issues", _
            strSupertip:="View the add-in project support issues on GitHub."

        AddCtl "btnGoToLinkDownload", "Download Latest Version", _
            strSupertip:="View the GitHub download page for this add-in project."

    ' Return dictionary
    Set GetRibbonStrings = m_dStrings

End Function


'---------------------------------------------------------------------------------------
' Procedure : AddCtl
' Author    : Adam Waller
' Date      : 10/29/2024
' Purpose   : Add an entry to the dictionary of translated property strings
'---------------------------------------------------------------------------------------
'
Private Sub AddCtl(strControl As String, strLabel As String, _
                        Optional strDescription As String, _
                        Optional strSupertip As String)
    Dim dControl As Dictionary
    Set dControl = New Dictionary
    With dControl
        .Add "Label", T(strLabel, "Ribbon." & strControl & ".Label")
        .Add "Description", T(strDescription, "Ribbon." & strControl & ".Description")
        .Add "Supertip", T(strSupertip, "Ribbon." & strControl & ".Supertip")
    End With
    m_dStrings.Add strControl, dControl
End Sub
