VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsPublic"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
'---------------------------------------------------------------------------------------
' Module    : clsPublic
' Author    : Adam Waller
' Date      : 11/25/2023
' Purpose   : This class is set to public creatable instancing.
'---------------------------------------------------------------------------------------

Option Compare Database
Option Explicit

Public MyProperty As String
